.TH modplug123 1 "February 21, 2011"
.SH NAME
modplug123 \- a commandline music mod player using libmodplug (ALSA)
.SH SYNOPSIS
.B modplug123
.RI [ options ] " files" ...
.br
.SH DESCRIPTION
This manual page documents briefly the
.B modplug123
command.
.PP
\fBmodplug123\fP is a command line player for many music modules
(669, amf, ams, dbm, dmf, dsm, far, it, j2b, mdl, med mod, mt2,
mtm, okt, psm, ptm, s3m, stm, ult, umx and xm) using the libmodplug library.
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-v, \-\-version
Show version of program.
.TP
.B \-l
Start in loop mode.
.B \-ao <audio output driver> 
Use specific libAO output driver, eg. -ao wav (file writing to output.wav) or alsa
.SH USAGE
When you have started modplugplay using some files to play, you can
control it using following keys
.IP "\fBl\fP   loop, unloop"
.IP "\fBp\fP   pause, unpause"
.IP "\fBr\fP   random song"
.IP "\fBn\fP   next song"
.IP "\fBN\fP   previous song"
.IP "\fBf\fP   forward ten seconds"
.IP "\fBb\fP   backward ten seconds"
.IP "\fB+\fP   louder"
.IP "\fB-\fP   softer"
.SH SEE ALSO
.BR modplug123 (1),
.BR schismtracker (1),
.BR milkytracker (1),
.BR protracker (1),
.BR fasttracker2 (1),
.BR klystrack (1),
.BR hivelytracker (1),
.BR goattracker (1),
.BR ccutter (1),
.BR ocp (1).
.SH MUSIC FILES
.IP http://www.maktone.tk/
.IP http://www.chiptune.com/
.IP http://www.chiptune.de/
.IP http://www.mickrippon.com/
.IP ftp://ftp.hornet.org/pub/demos/music/contests/
.SH AUTHOR
modplug123 was written by Konstanty Bialkowski.
